package com.wecodee.SpringBootPractice.admin.constant;

public enum EventTriggerName {
	
	 ACCOUNT_OPENED("ACCOUNT_OPENED"),
	    CUSTOMER_OPENED("CUSTOMER_OPENED"),
	    CUSTOMER_IB_NOT_REGISTERED("CUSTOMER_IB_NOT_REGISTERED"),
	    CUSTOMER_IB_BASIC_PACKAGE("CUSTOMER_IB_BASIC_PACKAGE"),
	    CUSTOMER_IB_FIRST_LOGIN("CUSTOMER_IB_FIRST_LOGIN"),
	    CUSTOMER_ANY_TRANSACTION("CUSTOMER_ANY_TRANSACTION"),
	    CUSTOMER_IB_FULL_PACKAGE("CUSTOMER_IB_FULL_PACKAGE"),
	    CUSTOMER_BRANCH_TRANSACTION("CUSTOMER_BRANCH_TRANSACTION"),
	    DEBIT_CARD_NOT_APPLIED("DEBIT_CARD_NOT_APPLIED"),
	    ANY_PACKAGE_NOT_APPLIED("ANY_PACKAGE_NOT_APPLIED"),
	    CUSTOMER_IB_INACTIVE("CUSTOMER_IB_INACTIVE"),
	    CUSTOMER_NO_TRANSACTION("CUSTOMER_NO_TRANSACTION"),
	    CREDIT_CARD_AVAILABLE("CREDIT_CARD_AVAILABLE"),
	    DEBIT_CARD_AVAILABLE("DEBIT_CARD_AVAILABLE"),
	    CREDIT_CARD_NOT_APPLIED("CREDIT_CARD_NOT_APPLIED"),
	    SAVINGS_ACCOUNT_NOT_AVAILABLE("SAVINGS_ACCOUNT_NOT_AVAILABLE"),
	    TERM_DEPOSIT_NOT_AVAILABLE("TERM_DEPOSIT_NOT_AVAILABLE"),
	    OVERDRAFT_NOT_AVAILABLE("OVERDRAFT_NOT_AVAILABLE");

	    private String name;

	    EventTriggerName(String name) {
	        this.name = name;
	    }

	    public String getName() {
	        return name;
	    }

}
