package com.wecodee.SpringBootPractice.admin.constant;

public enum Function {
	
    //FUNCTION NAMES
    //BASE
    LOGIN("LOGIN"),
    LOGOUT("LOGOUT"),
    //USER MANAGEMENT
    USER("USER"),
    ROLE("ROLE"),
    //MSG-CONFIG
    ATM("ATM"),
    BRANCH("BRANCH"),
    //CUSTOMER MANAGEMENT

    PROCESSFLOW("PROCESSFLOW"), //PROCESS FLOW
    CUSTOMERPROFILE("CUSTOMERPROFILE"),
    //NOTIFICATION CONFIGURATION
    EMAILTHEME("EMAILTHEME"),
    NOTIFICATIONTEMPLATE("NOTIFICATIONTEMPLATE"),
    NOTIFICATIONCONTROL("NOTIFICATIONCONTROL"),
    //APP CONFIGURATION
    EMAILCONFIG("EMAILCONFIG"),
    SMSCONFIG("SMSCONFIG"),
    SECURITYPARAMETER("SECURITYPARAMETER"),
    LOOKUP("LOOKUP"),
    //GROUP NOTIFICATION
    NOTIFICATIONGROUP("NOTIFICATIONGROUP"),
	BULKNOTIFICATION("BULKNOTIFICATION"),
    //CUSTOMER NOTIFICATION
    CUSTOMERJOURNEY("CUSTOMERJOURNEY"),
    CUSTOMERNOTIFICATION("CUSTOMERNOTIFICATION"),
    SPECIALDAY("SPECIALDAY");
	
	private String name;
	
	 private Function(String name) {
	        this.name = name;
	    }

	public String getName() {
		return name;
	}


}
